services:
  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: festino-admin
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - 5173:80
    restart: always
